export const BADGED_RATING_KEYS = [
  "0.0",
  "0.1",
  "0.2",
  "0.3",
  "0.4",
  "0.5",
  "0.6",
  "0.7",
  "0.8",
  "0.9",
  "1.0",
  "1.1",
  "1.2",
  "1.3",
  "1.4",
  "1.5",
  "1.6",
  "1.7",
  "1.8",
  "1.9",
  "2.0",
  "2.1",
  "2.2",
  "2.3",
  "2.4",
  "2.5",
  "2.6",
  "2.7",
  "2.8",
  "2.9",
  "3.0",
  "3.1",
  "3.2",
  "3.3",
  "3.4",
  "3.5",
  "3.6",
  "3.7",
  "3.8",
  "3.9",
  "4.0",
  "4.1",
  "4.2",
  "4.3",
  "4.4",
  "4.5",
  "4.6",
  "4.7",
  "4.8",
  "4.9",
  "5.0",
] as const;

export type BadgedRatingKey = (typeof BADGED_RATING_KEYS)[number];
export type BadgedCategory = "Fitness" | "Gastro" | "Relax" | "Beauty";

export const BADGED_ICON_SOURCES: Record<BadgedCategory, Record<BadgedRatingKey, number>> = {
  Fitness: {
    "0.0": require("../../images/icons/badged/fitness/fitness_rating_0.0.png"),
    "0.1": require("../../images/icons/badged/fitness/fitness_rating_0.1.png"),
    "0.2": require("../../images/icons/badged/fitness/fitness_rating_0.2.png"),
    "0.3": require("../../images/icons/badged/fitness/fitness_rating_0.3.png"),
    "0.4": require("../../images/icons/badged/fitness/fitness_rating_0.4.png"),
    "0.5": require("../../images/icons/badged/fitness/fitness_rating_0.5.png"),
    "0.6": require("../../images/icons/badged/fitness/fitness_rating_0.6.png"),
    "0.7": require("../../images/icons/badged/fitness/fitness_rating_0.7.png"),
    "0.8": require("../../images/icons/badged/fitness/fitness_rating_0.8.png"),
    "0.9": require("../../images/icons/badged/fitness/fitness_rating_0.9.png"),
    "1.0": require("../../images/icons/badged/fitness/fitness_rating_1.0.png"),
    "1.1": require("../../images/icons/badged/fitness/fitness_rating_1.1.png"),
    "1.2": require("../../images/icons/badged/fitness/fitness_rating_1.2.png"),
    "1.3": require("../../images/icons/badged/fitness/fitness_rating_1.3.png"),
    "1.4": require("../../images/icons/badged/fitness/fitness_rating_1.4.png"),
    "1.5": require("../../images/icons/badged/fitness/fitness_rating_1.5.png"),
    "1.6": require("../../images/icons/badged/fitness/fitness_rating_1.6.png"),
    "1.7": require("../../images/icons/badged/fitness/fitness_rating_1.7.png"),
    "1.8": require("../../images/icons/badged/fitness/fitness_rating_1.8.png"),
    "1.9": require("../../images/icons/badged/fitness/fitness_rating_1.9.png"),
    "2.0": require("../../images/icons/badged/fitness/fitness_rating_2.0.png"),
    "2.1": require("../../images/icons/badged/fitness/fitness_rating_2.1.png"),
    "2.2": require("../../images/icons/badged/fitness/fitness_rating_2.2.png"),
    "2.3": require("../../images/icons/badged/fitness/fitness_rating_2.3.png"),
    "2.4": require("../../images/icons/badged/fitness/fitness_rating_2.4.png"),
    "2.5": require("../../images/icons/badged/fitness/fitness_rating_2.5.png"),
    "2.6": require("../../images/icons/badged/fitness/fitness_rating_2.6.png"),
    "2.7": require("../../images/icons/badged/fitness/fitness_rating_2.7.png"),
    "2.8": require("../../images/icons/badged/fitness/fitness_rating_2.8.png"),
    "2.9": require("../../images/icons/badged/fitness/fitness_rating_2.9.png"),
    "3.0": require("../../images/icons/badged/fitness/fitness_rating_3.0.png"),
    "3.1": require("../../images/icons/badged/fitness/fitness_rating_3.1.png"),
    "3.2": require("../../images/icons/badged/fitness/fitness_rating_3.2.png"),
    "3.3": require("../../images/icons/badged/fitness/fitness_rating_3.3.png"),
    "3.4": require("../../images/icons/badged/fitness/fitness_rating_3.4.png"),
    "3.5": require("../../images/icons/badged/fitness/fitness_rating_3.5.png"),
    "3.6": require("../../images/icons/badged/fitness/fitness_rating_3.6.png"),
    "3.7": require("../../images/icons/badged/fitness/fitness_rating_3.7.png"),
    "3.8": require("../../images/icons/badged/fitness/fitness_rating_3.8.png"),
    "3.9": require("../../images/icons/badged/fitness/fitness_rating_3.9.png"),
    "4.0": require("../../images/icons/badged/fitness/fitness_rating_4.0.png"),
    "4.1": require("../../images/icons/badged/fitness/fitness_rating_4.1.png"),
    "4.2": require("../../images/icons/badged/fitness/fitness_rating_4.2.png"),
    "4.3": require("../../images/icons/badged/fitness/fitness_rating_4.3.png"),
    "4.4": require("../../images/icons/badged/fitness/fitness_rating_4.4.png"),
    "4.5": require("../../images/icons/badged/fitness/fitness_rating_4.5.png"),
    "4.6": require("../../images/icons/badged/fitness/fitness_rating_4.6.png"),
    "4.7": require("../../images/icons/badged/fitness/fitness_rating_4.7.png"),
    "4.8": require("../../images/icons/badged/fitness/fitness_rating_4.8.png"),
    "4.9": require("../../images/icons/badged/fitness/fitness_rating_4.9.png"),
    "5.0": require("../../images/icons/badged/fitness/fitness_rating_5.0.png"),
  },
  Gastro: {
    "0.0": require("../../images/icons/badged/gastro/gastro_rating_0.0.png"),
    "0.1": require("../../images/icons/badged/gastro/gastro_rating_0.1.png"),
    "0.2": require("../../images/icons/badged/gastro/gastro_rating_0.2.png"),
    "0.3": require("../../images/icons/badged/gastro/gastro_rating_0.3.png"),
    "0.4": require("../../images/icons/badged/gastro/gastro_rating_0.4.png"),
    "0.5": require("../../images/icons/badged/gastro/gastro_rating_0.5.png"),
    "0.6": require("../../images/icons/badged/gastro/gastro_rating_0.6.png"),
    "0.7": require("../../images/icons/badged/gastro/gastro_rating_0.7.png"),
    "0.8": require("../../images/icons/badged/gastro/gastro_rating_0.8.png"),
    "0.9": require("../../images/icons/badged/gastro/gastro_rating_0.9.png"),
    "1.0": require("../../images/icons/badged/gastro/gastro_rating_1.0.png"),
    "1.1": require("../../images/icons/badged/gastro/gastro_rating_1.1.png"),
    "1.2": require("../../images/icons/badged/gastro/gastro_rating_1.2.png"),
    "1.3": require("../../images/icons/badged/gastro/gastro_rating_1.3.png"),
    "1.4": require("../../images/icons/badged/gastro/gastro_rating_1.4.png"),
    "1.5": require("../../images/icons/badged/gastro/gastro_rating_1.5.png"),
    "1.6": require("../../images/icons/badged/gastro/gastro_rating_1.6.png"),
    "1.7": require("../../images/icons/badged/gastro/gastro_rating_1.7.png"),
    "1.8": require("../../images/icons/badged/gastro/gastro_rating_1.8.png"),
    "1.9": require("../../images/icons/badged/gastro/gastro_rating_1.9.png"),
    "2.0": require("../../images/icons/badged/gastro/gastro_rating_2.0.png"),
    "2.1": require("../../images/icons/badged/gastro/gastro_rating_2.1.png"),
    "2.2": require("../../images/icons/badged/gastro/gastro_rating_2.2.png"),
    "2.3": require("../../images/icons/badged/gastro/gastro_rating_2.3.png"),
    "2.4": require("../../images/icons/badged/gastro/gastro_rating_2.4.png"),
    "2.5": require("../../images/icons/badged/gastro/gastro_rating_2.5.png"),
    "2.6": require("../../images/icons/badged/gastro/gastro_rating_2.6.png"),
    "2.7": require("../../images/icons/badged/gastro/gastro_rating_2.7.png"),
    "2.8": require("../../images/icons/badged/gastro/gastro_rating_2.8.png"),
    "2.9": require("../../images/icons/badged/gastro/gastro_rating_2.9.png"),
    "3.0": require("../../images/icons/badged/gastro/gastro_rating_3.0.png"),
    "3.1": require("../../images/icons/badged/gastro/gastro_rating_3.1.png"),
    "3.2": require("../../images/icons/badged/gastro/gastro_rating_3.2.png"),
    "3.3": require("../../images/icons/badged/gastro/gastro_rating_3.3.png"),
    "3.4": require("../../images/icons/badged/gastro/gastro_rating_3.4.png"),
    "3.5": require("../../images/icons/badged/gastro/gastro_rating_3.5.png"),
    "3.6": require("../../images/icons/badged/gastro/gastro_rating_3.6.png"),
    "3.7": require("../../images/icons/badged/gastro/gastro_rating_3.7.png"),
    "3.8": require("../../images/icons/badged/gastro/gastro_rating_3.8.png"),
    "3.9": require("../../images/icons/badged/gastro/gastro_rating_3.9.png"),
    "4.0": require("../../images/icons/badged/gastro/gastro_rating_4.0.png"),
    "4.1": require("../../images/icons/badged/gastro/gastro_rating_4.1.png"),
    "4.2": require("../../images/icons/badged/gastro/gastro_rating_4.2.png"),
    "4.3": require("../../images/icons/badged/gastro/gastro_rating_4.3.png"),
    "4.4": require("../../images/icons/badged/gastro/gastro_rating_4.4.png"),
    "4.5": require("../../images/icons/badged/gastro/gastro_rating_4.5.png"),
    "4.6": require("../../images/icons/badged/gastro/gastro_rating_4.6.png"),
    "4.7": require("../../images/icons/badged/gastro/gastro_rating_4.7.png"),
    "4.8": require("../../images/icons/badged/gastro/gastro_rating_4.8.png"),
    "4.9": require("../../images/icons/badged/gastro/gastro_rating_4.9.png"),
    "5.0": require("../../images/icons/badged/gastro/gastro_rating_5.0.png"),
  },
  Relax: {
    "0.0": require("../../images/icons/badged/relax/relax_rating_0.0.png"),
    "0.1": require("../../images/icons/badged/relax/relax_rating_0.1.png"),
    "0.2": require("../../images/icons/badged/relax/relax_rating_0.2.png"),
    "0.3": require("../../images/icons/badged/relax/relax_rating_0.3.png"),
    "0.4": require("../../images/icons/badged/relax/relax_rating_0.4.png"),
    "0.5": require("../../images/icons/badged/relax/relax_rating_0.5.png"),
    "0.6": require("../../images/icons/badged/relax/relax_rating_0.6.png"),
    "0.7": require("../../images/icons/badged/relax/relax_rating_0.7.png"),
    "0.8": require("../../images/icons/badged/relax/relax_rating_0.8.png"),
    "0.9": require("../../images/icons/badged/relax/relax_rating_0.9.png"),
    "1.0": require("../../images/icons/badged/relax/relax_rating_1.0.png"),
    "1.1": require("../../images/icons/badged/relax/relax_rating_1.1.png"),
    "1.2": require("../../images/icons/badged/relax/relax_rating_1.2.png"),
    "1.3": require("../../images/icons/badged/relax/relax_rating_1.3.png"),
    "1.4": require("../../images/icons/badged/relax/relax_rating_1.4.png"),
    "1.5": require("../../images/icons/badged/relax/relax_rating_1.5.png"),
    "1.6": require("../../images/icons/badged/relax/relax_rating_1.6.png"),
    "1.7": require("../../images/icons/badged/relax/relax_rating_1.7.png"),
    "1.8": require("../../images/icons/badged/relax/relax_rating_1.8.png"),
    "1.9": require("../../images/icons/badged/relax/relax_rating_1.9.png"),
    "2.0": require("../../images/icons/badged/relax/relax_rating_2.0.png"),
    "2.1": require("../../images/icons/badged/relax/relax_rating_2.1.png"),
    "2.2": require("../../images/icons/badged/relax/relax_rating_2.2.png"),
    "2.3": require("../../images/icons/badged/relax/relax_rating_2.3.png"),
    "2.4": require("../../images/icons/badged/relax/relax_rating_2.4.png"),
    "2.5": require("../../images/icons/badged/relax/relax_rating_2.5.png"),
    "2.6": require("../../images/icons/badged/relax/relax_rating_2.6.png"),
    "2.7": require("../../images/icons/badged/relax/relax_rating_2.7.png"),
    "2.8": require("../../images/icons/badged/relax/relax_rating_2.8.png"),
    "2.9": require("../../images/icons/badged/relax/relax_rating_2.9.png"),
    "3.0": require("../../images/icons/badged/relax/relax_rating_3.0.png"),
    "3.1": require("../../images/icons/badged/relax/relax_rating_3.1.png"),
    "3.2": require("../../images/icons/badged/relax/relax_rating_3.2.png"),
    "3.3": require("../../images/icons/badged/relax/relax_rating_3.3.png"),
    "3.4": require("../../images/icons/badged/relax/relax_rating_3.4.png"),
    "3.5": require("../../images/icons/badged/relax/relax_rating_3.5.png"),
    "3.6": require("../../images/icons/badged/relax/relax_rating_3.6.png"),
    "3.7": require("../../images/icons/badged/relax/relax_rating_3.7.png"),
    "3.8": require("../../images/icons/badged/relax/relax_rating_3.8.png"),
    "3.9": require("../../images/icons/badged/relax/relax_rating_3.9.png"),
    "4.0": require("../../images/icons/badged/relax/relax_rating_4.0.png"),
    "4.1": require("../../images/icons/badged/relax/relax_rating_4.1.png"),
    "4.2": require("../../images/icons/badged/relax/relax_rating_4.2.png"),
    "4.3": require("../../images/icons/badged/relax/relax_rating_4.3.png"),
    "4.4": require("../../images/icons/badged/relax/relax_rating_4.4.png"),
    "4.5": require("../../images/icons/badged/relax/relax_rating_4.5.png"),
    "4.6": require("../../images/icons/badged/relax/relax_rating_4.6.png"),
    "4.7": require("../../images/icons/badged/relax/relax_rating_4.7.png"),
    "4.8": require("../../images/icons/badged/relax/relax_rating_4.8.png"),
    "4.9": require("../../images/icons/badged/relax/relax_rating_4.9.png"),
    "5.0": require("../../images/icons/badged/relax/relax_rating_5.0.png"),
  },
  Beauty: {
    "0.0": require("../../images/icons/badged/beauty/beauty_rating_0.0.png"),
    "0.1": require("../../images/icons/badged/beauty/beauty_rating_0.1.png"),
    "0.2": require("../../images/icons/badged/beauty/beauty_rating_0.2.png"),
    "0.3": require("../../images/icons/badged/beauty/beauty_rating_0.3.png"),
    "0.4": require("../../images/icons/badged/beauty/beauty_rating_0.4.png"),
    "0.5": require("../../images/icons/badged/beauty/beauty_rating_0.5.png"),
    "0.6": require("../../images/icons/badged/beauty/beauty_rating_0.6.png"),
    "0.7": require("../../images/icons/badged/beauty/beauty_rating_0.7.png"),
    "0.8": require("../../images/icons/badged/beauty/beauty_rating_0.8.png"),
    "0.9": require("../../images/icons/badged/beauty/beauty_rating_0.9.png"),
    "1.0": require("../../images/icons/badged/beauty/beauty_rating_1.0.png"),
    "1.1": require("../../images/icons/badged/beauty/beauty_rating_1.1.png"),
    "1.2": require("../../images/icons/badged/beauty/beauty_rating_1.2.png"),
    "1.3": require("../../images/icons/badged/beauty/beauty_rating_1.3.png"),
    "1.4": require("../../images/icons/badged/beauty/beauty_rating_1.4.png"),
    "1.5": require("../../images/icons/badged/beauty/beauty_rating_1.5.png"),
    "1.6": require("../../images/icons/badged/beauty/beauty_rating_1.6.png"),
    "1.7": require("../../images/icons/badged/beauty/beauty_rating_1.7.png"),
    "1.8": require("../../images/icons/badged/beauty/beauty_rating_1.8.png"),
    "1.9": require("../../images/icons/badged/beauty/beauty_rating_1.9.png"),
    "2.0": require("../../images/icons/badged/beauty/beauty_rating_2.0.png"),
    "2.1": require("../../images/icons/badged/beauty/beauty_rating_2.1.png"),
    "2.2": require("../../images/icons/badged/beauty/beauty_rating_2.2.png"),
    "2.3": require("../../images/icons/badged/beauty/beauty_rating_2.3.png"),
    "2.4": require("../../images/icons/badged/beauty/beauty_rating_2.4.png"),
    "2.5": require("../../images/icons/badged/beauty/beauty_rating_2.5.png"),
    "2.6": require("../../images/icons/badged/beauty/beauty_rating_2.6.png"),
    "2.7": require("../../images/icons/badged/beauty/beauty_rating_2.7.png"),
    "2.8": require("../../images/icons/badged/beauty/beauty_rating_2.8.png"),
    "2.9": require("../../images/icons/badged/beauty/beauty_rating_2.9.png"),
    "3.0": require("../../images/icons/badged/beauty/beauty_rating_3.0.png"),
    "3.1": require("../../images/icons/badged/beauty/beauty_rating_3.1.png"),
    "3.2": require("../../images/icons/badged/beauty/beauty_rating_3.2.png"),
    "3.3": require("../../images/icons/badged/beauty/beauty_rating_3.3.png"),
    "3.4": require("../../images/icons/badged/beauty/beauty_rating_3.4.png"),
    "3.5": require("../../images/icons/badged/beauty/beauty_rating_3.5.png"),
    "3.6": require("../../images/icons/badged/beauty/beauty_rating_3.6.png"),
    "3.7": require("../../images/icons/badged/beauty/beauty_rating_3.7.png"),
    "3.8": require("../../images/icons/badged/beauty/beauty_rating_3.8.png"),
    "3.9": require("../../images/icons/badged/beauty/beauty_rating_3.9.png"),
    "4.0": require("../../images/icons/badged/beauty/beauty_rating_4.0.png"),
    "4.1": require("../../images/icons/badged/beauty/beauty_rating_4.1.png"),
    "4.2": require("../../images/icons/badged/beauty/beauty_rating_4.2.png"),
    "4.3": require("../../images/icons/badged/beauty/beauty_rating_4.3.png"),
    "4.4": require("../../images/icons/badged/beauty/beauty_rating_4.4.png"),
    "4.5": require("../../images/icons/badged/beauty/beauty_rating_4.5.png"),
    "4.6": require("../../images/icons/badged/beauty/beauty_rating_4.6.png"),
    "4.7": require("../../images/icons/badged/beauty/beauty_rating_4.7.png"),
    "4.8": require("../../images/icons/badged/beauty/beauty_rating_4.8.png"),
    "4.9": require("../../images/icons/badged/beauty/beauty_rating_4.9.png"),
    "5.0": require("../../images/icons/badged/beauty/beauty_rating_5.0.png"),
  },
};
