export const CLUSTER_COUNT_KEYS = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "90",
  "91",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "99",
] as const;

export type ClusterCountKey = (typeof CLUSTER_COUNT_KEYS)[number];

export const CLUSTER_ICON_SOURCES: Record<ClusterCountKey, number> = {
  "0": require("../../images/icons/cluster/cluster_0.png"),
  "1": require("../../images/icons/cluster/cluster_1.png"),
  "2": require("../../images/icons/cluster/cluster_2.png"),
  "3": require("../../images/icons/cluster/cluster_3.png"),
  "4": require("../../images/icons/cluster/cluster_4.png"),
  "5": require("../../images/icons/cluster/cluster_5.png"),
  "6": require("../../images/icons/cluster/cluster_6.png"),
  "7": require("../../images/icons/cluster/cluster_7.png"),
  "8": require("../../images/icons/cluster/cluster_8.png"),
  "9": require("../../images/icons/cluster/cluster_9.png"),
  "10": require("../../images/icons/cluster/cluster_10.png"),
  "11": require("../../images/icons/cluster/cluster_11.png"),
  "12": require("../../images/icons/cluster/cluster_12.png"),
  "13": require("../../images/icons/cluster/cluster_13.png"),
  "14": require("../../images/icons/cluster/cluster_14.png"),
  "15": require("../../images/icons/cluster/cluster_15.png"),
  "16": require("../../images/icons/cluster/cluster_16.png"),
  "17": require("../../images/icons/cluster/cluster_17.png"),
  "18": require("../../images/icons/cluster/cluster_18.png"),
  "19": require("../../images/icons/cluster/cluster_19.png"),
  "20": require("../../images/icons/cluster/cluster_20.png"),
  "21": require("../../images/icons/cluster/cluster_21.png"),
  "22": require("../../images/icons/cluster/cluster_22.png"),
  "23": require("../../images/icons/cluster/cluster_23.png"),
  "24": require("../../images/icons/cluster/cluster_24.png"),
  "25": require("../../images/icons/cluster/cluster_25.png"),
  "26": require("../../images/icons/cluster/cluster_26.png"),
  "27": require("../../images/icons/cluster/cluster_27.png"),
  "28": require("../../images/icons/cluster/cluster_28.png"),
  "29": require("../../images/icons/cluster/cluster_29.png"),
  "30": require("../../images/icons/cluster/cluster_30.png"),
  "31": require("../../images/icons/cluster/cluster_31.png"),
  "32": require("../../images/icons/cluster/cluster_32.png"),
  "33": require("../../images/icons/cluster/cluster_33.png"),
  "34": require("../../images/icons/cluster/cluster_34.png"),
  "35": require("../../images/icons/cluster/cluster_35.png"),
  "36": require("../../images/icons/cluster/cluster_36.png"),
  "37": require("../../images/icons/cluster/cluster_37.png"),
  "38": require("../../images/icons/cluster/cluster_38.png"),
  "39": require("../../images/icons/cluster/cluster_39.png"),
  "40": require("../../images/icons/cluster/cluster_40.png"),
  "41": require("../../images/icons/cluster/cluster_41.png"),
  "42": require("../../images/icons/cluster/cluster_42.png"),
  "43": require("../../images/icons/cluster/cluster_43.png"),
  "44": require("../../images/icons/cluster/cluster_44.png"),
  "45": require("../../images/icons/cluster/cluster_45.png"),
  "46": require("../../images/icons/cluster/cluster_46.png"),
  "47": require("../../images/icons/cluster/cluster_47.png"),
  "48": require("../../images/icons/cluster/cluster_48.png"),
  "49": require("../../images/icons/cluster/cluster_49.png"),
  "50": require("../../images/icons/cluster/cluster_50.png"),
  "51": require("../../images/icons/cluster/cluster_51.png"),
  "52": require("../../images/icons/cluster/cluster_52.png"),
  "53": require("../../images/icons/cluster/cluster_53.png"),
  "54": require("../../images/icons/cluster/cluster_54.png"),
  "55": require("../../images/icons/cluster/cluster_55.png"),
  "56": require("../../images/icons/cluster/cluster_56.png"),
  "57": require("../../images/icons/cluster/cluster_57.png"),
  "58": require("../../images/icons/cluster/cluster_58.png"),
  "59": require("../../images/icons/cluster/cluster_59.png"),
  "60": require("../../images/icons/cluster/cluster_60.png"),
  "61": require("../../images/icons/cluster/cluster_61.png"),
  "62": require("../../images/icons/cluster/cluster_62.png"),
  "63": require("../../images/icons/cluster/cluster_63.png"),
  "64": require("../../images/icons/cluster/cluster_64.png"),
  "65": require("../../images/icons/cluster/cluster_65.png"),
  "66": require("../../images/icons/cluster/cluster_66.png"),
  "67": require("../../images/icons/cluster/cluster_67.png"),
  "68": require("../../images/icons/cluster/cluster_68.png"),
  "69": require("../../images/icons/cluster/cluster_69.png"),
  "70": require("../../images/icons/cluster/cluster_70.png"),
  "71": require("../../images/icons/cluster/cluster_71.png"),
  "72": require("../../images/icons/cluster/cluster_72.png"),
  "73": require("../../images/icons/cluster/cluster_73.png"),
  "74": require("../../images/icons/cluster/cluster_74.png"),
  "75": require("../../images/icons/cluster/cluster_75.png"),
  "76": require("../../images/icons/cluster/cluster_76.png"),
  "77": require("../../images/icons/cluster/cluster_77.png"),
  "78": require("../../images/icons/cluster/cluster_78.png"),
  "79": require("../../images/icons/cluster/cluster_79.png"),
  "80": require("../../images/icons/cluster/cluster_80.png"),
  "81": require("../../images/icons/cluster/cluster_81.png"),
  "82": require("../../images/icons/cluster/cluster_82.png"),
  "83": require("../../images/icons/cluster/cluster_83.png"),
  "84": require("../../images/icons/cluster/cluster_84.png"),
  "85": require("../../images/icons/cluster/cluster_85.png"),
  "86": require("../../images/icons/cluster/cluster_86.png"),
  "87": require("../../images/icons/cluster/cluster_87.png"),
  "88": require("../../images/icons/cluster/cluster_88.png"),
  "89": require("../../images/icons/cluster/cluster_89.png"),
  "90": require("../../images/icons/cluster/cluster_90.png"),
  "91": require("../../images/icons/cluster/cluster_91.png"),
  "92": require("../../images/icons/cluster/cluster_92.png"),
  "93": require("../../images/icons/cluster/cluster_93.png"),
  "94": require("../../images/icons/cluster/cluster_94.png"),
  "95": require("../../images/icons/cluster/cluster_95.png"),
  "96": require("../../images/icons/cluster/cluster_96.png"),
  "97": require("../../images/icons/cluster/cluster_97.png"),
  "98": require("../../images/icons/cluster/cluster_98.png"),
  "99": require("../../images/icons/cluster/cluster_99.png"),
};
