/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-ios-compact-pins.ts
// Text-free compact pin sprites matching the old badged source frame, but without the rating badge.

export const IOS_COMPACT_PIN_BY_CATEGORY: Partial<Record<string, number>> = {
  Beauty: require("../../images/icons/ios-scaled/compact-pins/beauty.png"),
  Fitness: require("../../images/icons/ios-scaled/compact-pins/fitness.png"),
  Gastro: require("../../images/icons/ios-scaled/compact-pins/gastro.png"),
  Relax: require("../../images/icons/ios-scaled/compact-pins/relax.png"),
  Multi: require("../../images/icons/ios-scaled/compact-pins/multi.png"),
};

// Anchor for compact pin sprites: pin tip at 95% of the 104x141 draw area,
// offset to (149, 134) on the 402x172 canvas -> anchor ~= (0.492, 0.779).
export const IOS_COMPACT_PIN_ANCHOR = { x: 0.492, y: 0.779 } as const;
