/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/normalize-ios-stacked-markers.ts

export const IOS_SCALED_STACKED_BY_COUNT: Partial<Record<number, number>> = {
  2: require("../../images/icons/ios-scaled/stacked-normalized/stacked_2.png"),
  3: require("../../images/icons/ios-scaled/stacked-normalized/stacked_3.png"),
  4: require("../../images/icons/ios-scaled/stacked-normalized/stacked_4.png"),
  5: require("../../images/icons/ios-scaled/stacked-normalized/stacked_5.png"),
  6: require("../../images/icons/ios-scaled/stacked-normalized/stacked_6.png"),
};
