/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-full-marker-sprites.mjs

export type FullMarkerSpriteEntry = {
  image: number;
  anchor: { x: number; y: number };
  width: number;
  height: number;
};

export const FULL_MARKER_CANVAS_WIDTH = 260;
export const FULL_MARKER_CANVAS_HEIGHT = 276;
export const FULL_MARKER_DEFAULT_ANCHOR = {
  x: 0.5,
  y: 0.786231884058,
} as const;

export const FULL_MARKER_SPRITES: Record<string, FullMarkerSpriteEntry> = {
  "aero_bistro_janikovce": {
    image: require("../../images/icons/full-markers/aero_bistro_janikovce_rqrit3.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 462,
    height: 276,
  },
  "artin_restaurant": {
    image: require("../../images/icons/full-markers/artin_restaurant_rys0ql.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 375,
    height: 276,
  },
  "balance_beauty_nitra": {
    image: require("../../images/icons/full-markers/balance_beauty_nitra_12pgzzh.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 448,
    height: 276,
  },
  "bar_u_dvoch_sestier": {
    image: require("../../images/icons/full-markers/bar_u_dvoch_sestier_1uivhwr.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 419,
    height: 276,
  },
  "bc_burger": {
    image: require("../../images/icons/full-markers/bc_burger_1w5wx8i.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "beauty_style": {
    image: require("../../images/icons/full-markers/beauty_style_3zvwhr.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 298,
    height: 276,
  },
  "biotechusa": {
    image: require("../../images/icons/full-markers/biotechusa_1isoeu8.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 269,
    height: 276,
  },
  "bistro_harley": {
    image: require("../../images/icons/full-markers/bistro_harley_nh2rnu.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 316,
    height: 276,
  },
  "bistro_maurus": {
    image: require("../../images/icons/full-markers/bistro_maurus_u449ls.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 324,
    height: 276,
  },
  "bistro_u_havrana": {
    image: require("../../images/icons/full-markers/bistro_u_havrana_1x59bk0.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 370,
    height: 276,
  },
  "bodyworld_fitness": {
    image: require("../../images/icons/full-markers/bodyworld_fitness_1ll9ln0.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 405,
    height: 276,
  },
  "cafe_bistro_medic": {
    image: require("../../images/icons/full-markers/cafe_bistro_medic_eh6e2d.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 379,
    height: 276,
  },
  "caffe_comfort_nitra": {
    image: require("../../images/icons/full-markers/caffe_comfort_nitra_vlqgo2.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 430,
    height: 276,
  },
  "cajdolska_viecha": {
    image: require("../../images/icons/full-markers/cajdolska_viecha_awh77o.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 378,
    height: 276,
  },
  "cajovna_dobrych_ludi": {
    image: require("../../images/icons/full-markers/cajovna_dobrych_ludi_86xwn6.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 453,
    height: 276,
  },
  "cajovna_epicure": {
    image: require("../../images/icons/full-markers/cajovna_epicure_1udqdcb.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 358,
    height: 276,
  },
  "cajovna_uno_nitra": {
    image: require("../../images/icons/full-markers/cajovna_uno_nitra_13hcayb.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 391,
    height: 276,
  },
  "castellum_cafe_nitra": {
    image: require("../../images/icons/full-markers/castellum_cafe_nitra_cefw9k.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 445,
    height: 276,
  },
  "center_stack_beauty": {
    image: require("../../images/icons/full-markers/center_stack_beauty_1en9s6s.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 435,
    height: 276,
  },
  "center_stack_bistro": {
    image: require("../../images/icons/full-markers/center_stack_bistro_zg96nl.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 425,
    height: 276,
  },
  "center_stack_relax": {
    image: require("../../images/icons/full-markers/center_stack_relax_yfpoiy.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 413,
    height: 276,
  },
  "ceska_hospudka_u_slovaka": {
    image: require("../../images/icons/full-markers/ceska_hospudka_u_slovaka_1yinfjm.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 536,
    height: 276,
  },
  "city_sports_nitra": {
    image: require("../../images/icons/full-markers/city_sports_nitra_1getuth.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 370,
    height: 276,
  },
  "coffee_tree_friends": {
    image: require("../../images/icons/full-markers/coffee_tree_friends_pfedh0.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 421,
    height: 276,
  },
  "Diamond barber": {
    image: require("../../images/icons/full-markers/diamond_barber_y45rr3.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 350,
    height: 276,
  },
  "Diamond gym": {
    image: require("../../images/icons/full-markers/diamond_gym_16d7fq8.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 290,
    height: 276,
  },
  "diamond_barbershop": {
    image: require("../../images/icons/full-markers/diamond_barbershop_18bfoy.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 436,
    height: 276,
  },
  "diamond_gym": {
    image: require("../../images/icons/full-markers/diamond_gym_1jyaj9v.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 290,
    height: 276,
  },
  "dinero_pizza_drazovce": {
    image: require("../../images/icons/full-markers/dinero_pizza_drazovce_1ag9s8y.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 458,
    height: 276,
  },
  "exisport_centro_nitra": {
    image: require("../../images/icons/full-markers/exisport_centro_nitra_pqo4zw.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 457,
    height: 276,
  },
  "fabrique_fitness": {
    image: require("../../images/icons/full-markers/fabrique_fitness_18jrff3.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 361,
    height: 276,
  },
  "fashion_k_z_nitra": {
    image: require("../../images/icons/full-markers/fashion_k_z_nitra_104o41d.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 360,
    height: 276,
  },
  "fit_bar_nitra": {
    image: require("../../images/icons/full-markers/fit_bar_nitra_1gytd03.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 289,
    height: 276,
  },
  "fit_club_olympia": {
    image: require("../../images/icons/full-markers/fit_club_olympia_1h8vptr.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 349,
    height: 276,
  },
  "fitcentrum_linia": {
    image: require("../../images/icons/full-markers/fitcentrum_linia_yujx3g.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 352,
    height: 276,
  },
  "for_sport_nitra": {
    image: require("../../images/icons/full-markers/for_sport_nitra_1buepac.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 345,
    height: 276,
  },
  "fyzio_romy": {
    image: require("../../images/icons/full-markers/fyzio_romy_11c8p46.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "gym_365": {
    image: require("../../images/icons/full-markers/gym_365_1v1u63n.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "gym_klub": {
    image: require("../../images/icons/full-markers/gym_klub_10qzt9.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "chill_cafe_nitra": {
    image: require("../../images/icons/full-markers/chill_cafe_nitra_txpfa6.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 348,
    height: 276,
  },
  "intersport_mlyny_nitra": {
    image: require("../../images/icons/full-markers/intersport_mlyny_nitra_5o2f5a.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 474,
    height: 276,
  },
  "intersport_promenada_nitra": {
    image: require("../../images/icons/full-markers/intersport_promenada_nitra_1ikncp4.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 568,
    height: 276,
  },
  "kadernictvo_affinage": {
    image: require("../../images/icons/full-markers/kadernictvo_affinage_1bgxq4d.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 451,
    height: 276,
  },
  "kadernictvo_katarina": {
    image: require("../../images/icons/full-markers/kadernictvo_katarina_1usatxh.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 451,
    height: 276,
  },
  "kadernictvo_klier_centro": {
    image: require("../../images/icons/full-markers/kadernictvo_klier_centro_1wsckid.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 524,
    height: 276,
  },
  "kadernictvo_klier_promenada": {
    image: require("../../images/icons/full-markers/kadernictvo_klier_promenada_1b5g663.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 594,
    height: 276,
  },
  "kadernictvo_kozmetika": {
    image: require("../../images/icons/full-markers/kadernictvo_kozmetika_stg7lr.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 477,
    height: 276,
  },
  "kadernictvo_naty_nitra": {
    image: require("../../images/icons/full-markers/kadernictvo_naty_nitra_1mdqlc9.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 478,
    height: 276,
  },
  "kadernictvo_pelikan": {
    image: require("../../images/icons/full-markers/kadernictvo_pelikan_15ktxs.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 431,
    height: 276,
  },
  "karla_restaurant_nitra": {
    image: require("../../images/icons/full-markers/karla_restaurant_nitra_1k0e7y9.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 487,
    height: 276,
  },
  "kebab_bistro_chrenovska": {
    image: require("../../images/icons/full-markers/kebab_bistro_chrenovska_wc3tqd.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 521,
    height: 276,
  },
  "kelo_gym": {
    image: require("../../images/icons/full-markers/kelo_gym_1mu6fw4.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "kozmeticky_salon_lenka": {
    image: require("../../images/icons/full-markers/kozmeticky_salon_lenka_dfp99.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 493,
    height: 276,
  },
  "kozmetika_lussy": {
    image: require("../../images/icons/full-markers/kozmetika_lussy_1618o79.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 356,
    height: 276,
  },
  "kozmetika_solarium_kadernictvo": {
    image: require("../../images/icons/full-markers/kozmetika_solarium_kadernictvo_1ar55ns.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 644,
    height: 276,
  },
  "la_marina_nitra": {
    image: require("../../images/icons/full-markers/la_marina_nitra_114a1s8.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 337,
    height: 276,
  },
  "marianska_stack_gastro": {
    image: require("../../images/icons/full-markers/marianska_stack_gastro_tr2xpy.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 499,
    height: 276,
  },
  "marianska_stack_gastro_2": {
    image: require("../../images/icons/full-markers/marianska_stack_gastro_2_1ysxvuj.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 524,
    height: 276,
  },
  "mcdonalds_chrenova": {
    image: require("../../images/icons/full-markers/mcdonalds_chrenova_3gf3w3.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 443,
    height: 276,
  },
  "media_cafe_restaurant": {
    image: require("../../images/icons/full-markers/media_cafe_restaurant_e5r1z5.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 469,
    height: 276,
  },
  "misap_thai_massage": {
    image: require("../../images/icons/full-markers/misap_thai_massage_37isxg.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 403,
    height: 276,
  },
  "natali_hair_nitra": {
    image: require("../../images/icons/full-markers/natali_hair_nitra_156gj6o.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 358,
    height: 276,
  },
  "nechtove_studio_kremnicka": {
    image: require("../../images/icons/full-markers/nechtove_studio_kremnicka_dz896y.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 550,
    height: 276,
  },
  "park_espresso_nitra": {
    image: require("../../images/icons/full-markers/park_espresso_nitra_1mi50ov.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 427,
    height: 276,
  },
  "parovske_haje_center": {
    image: require("../../images/icons/full-markers/parovske_haje_center_plkny7.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 457,
    height: 276,
  },
  "piano_cafe_nitra": {
    image: require("../../images/icons/full-markers/piano_cafe_nitra_1v0xsp7.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 355,
    height: 276,
  },
  "pizza_diamo_nitra": {
    image: require("../../images/icons/full-markers/pizza_diamo_nitra_12hwm8d.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 364,
    height: 276,
  },
  "pizza_nitra": {
    image: require("../../images/icons/full-markers/pizza_nitra_1jma50k.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "pko_nitra": {
    image: require("../../images/icons/full-markers/pko_nitra_1844e9s.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "posilnovna_chalupkova": {
    image: require("../../images/icons/full-markers/posilnovna_chalupkova_btmljr.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 486,
    height: 276,
  },
  "restauracia_naj_krskany": {
    image: require("../../images/icons/full-markers/restauracia_naj_krskany_khmp8x.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 511,
    height: 276,
  },
  "riverside_nitra": {
    image: require("../../images/icons/full-markers/riverside_nitra_ek2127.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 332,
    height: 276,
  },
  "sakura_nitra_central": {
    image: require("../../images/icons/full-markers/sakura_nitra_central_1sfjf5v.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 448,
    height: 276,
  },
  "salon_krasy_xoxo": {
    image: require("../../images/icons/full-markers/salon_krasy_xoxo_x0lpny.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 383,
    height: 276,
  },
  "salon_maria_nitra": {
    image: require("../../images/icons/full-markers/salon_maria_nitra_4doj3e.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 381,
    height: 276,
  },
  "salon_shine": {
    image: require("../../images/icons/full-markers/salon_shine_8t1o5m.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 276,
    height: 276,
  },
  "soy_beauty": {
    image: require("../../images/icons/full-markers/soy_beauty_1bodsrj.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 265,
    height: 276,
  },
  "sport_caffe_nitra": {
    image: require("../../images/icons/full-markers/sport_caffe_nitra_aecc80.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 382,
    height: 276,
  },
  "sportisimo_centro_nitra": {
    image: require("../../images/icons/full-markers/sportisimo_centro_nitra_rtdqgd.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 494,
    height: 276,
  },
  "sportisimo_galeria_nitra": {
    image: require("../../images/icons/full-markers/sportisimo_galeria_nitra_nvhv13.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 501,
    height: 276,
  },
  "staromestska_pivaren": {
    image: require("../../images/icons/full-markers/staromestska_pivaren_1nbgmh0.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 458,
    height: 276,
  },
  "tantal_mlynarce": {
    image: require("../../images/icons/full-markers/tantal_mlynarce_paqh1r.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 361,
    height: 276,
  },
  "tardis_cokina": {
    image: require("../../images/icons/full-markers/tardis_cokina_dadsmu.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 307,
    height: 276,
  },
  "tayberr_massage": {
    image: require("../../images/icons/full-markers/tayberr_massage_hxhxq4.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 371,
    height: 276,
  },
  "top_sport_gym": {
    image: require("../../images/icons/full-markers/top_sport_gym_1ymtv25.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 319,
    height: 276,
  },
  "u_zlatej_svini": {
    image: require("../../images/icons/full-markers/u_zlatej_svini_yumoof.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 298,
    height: 276,
  },
  "viet_nails_nitra": {
    image: require("../../images/icons/full-markers/viet_nails_nitra_ia8uiu.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 336,
    height: 276,
  },
  "vita_verde": {
    image: require("../../images/icons/full-markers/vita_verde_1owqu6i.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 260,
    height: 276,
  },
  "wellness_zoborska": {
    image: require("../../images/icons/full-markers/wellness_zoborska_e115o.png"),
    anchor: FULL_MARKER_DEFAULT_ANCHOR,
    width: 417,
    height: 276,
  },
};

export const getLocalFullMarkerSprite = (spriteKey?: string | null) => {
  if (!spriteKey) {
    return undefined;
  }
  return FULL_MARKER_SPRITES[spriteKey];
};

export const hasLocalFullMarkerSpriteKey = (spriteKey?: string | null) =>
  Boolean(spriteKey && FULL_MARKER_SPRITES[spriteKey]);
