import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createCanvas, loadImage } from "canvas";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

// Locked uniform iOS full-sprite canvas – must match normalize-ios-full-markers.ts
const CANVAS_WIDTH = 322;
const CANVAS_HEIGHT = 138;
const PIN_ICON_WIDTH = 83;
const PIN_ICON_HEIGHT = 113;
const PIN_OFFSET_X = Math.round((CANVAS_WIDTH - PIN_ICON_WIDTH) / 2);
const PIN_OFFSET_Y = 0;

const GENERATED_FILE = path.join(ROOT_DIR, "lib/maps/generatedIOSScaledClusterByCount.ts");

const SOURCES = [
  {
    sourceDir: path.join(ROOT_DIR, "images/icons/cluster"),
    targetDir: path.join(ROOT_DIR, "images/icons/ios-scaled/cluster-normalized"),
    exportName: "IOS_SCALED_CLUSTER_BY_COUNT",
    targetRelPrefix: "images/icons/ios-scaled/cluster-normalized",
  },
  {
    sourceDir: path.join(ROOT_DIR, "images/icons/cluster_orange"),
    targetDir: path.join(ROOT_DIR, "images/icons/ios-scaled/cluster-orange-normalized"),
    exportName: "IOS_SCALED_FILTER_CLUSTER_BY_COUNT",
    targetRelPrefix: "images/icons/ios-scaled/cluster-orange-normalized",
  },
] as const;

const CLUSTER_COUNTS = Array.from({ length: 100 }, (_, i) => i) as number[];

const normalizeToPosix = (value: string) => value.replace(/\\/g, "/");

const run = async () => {
  const exportBlocks: string[] = [];

  for (const { sourceDir, targetDir, exportName, targetRelPrefix } of SOURCES) {
    fs.mkdirSync(targetDir, { recursive: true });
    const entries: Array<{ count: number; targetRelative: string }> = [];

    for (const count of CLUSTER_COUNTS) {
      const sourcePath = path.join(sourceDir, `cluster_${count}.png`);
      if (!fs.existsSync(sourcePath)) {
        console.warn(`[normalize-ios-cluster-markers] missing source: ${sourcePath}`);
        continue;
      }

      const targetFileName = `cluster_${count}.png`;
      const targetPath = path.join(targetDir, targetFileName);

      const sourceImage = await loadImage(sourcePath);
      const canvas = createCanvas(CANVAS_WIDTH, CANVAS_HEIGHT);
      const ctx = canvas.getContext("2d");
      ctx.clearRect(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);
      ctx.drawImage(sourceImage, PIN_OFFSET_X, PIN_OFFSET_Y, PIN_ICON_WIDTH, PIN_ICON_HEIGHT);

      fs.writeFileSync(targetPath, canvas.toBuffer("image/png"));

      const targetRelative = normalizeToPosix(
        path.relative(ROOT_DIR, targetPath)
      );
      entries.push({ count, targetRelative });
    }

    console.log(
      `[normalize-ios-cluster-markers] ${exportName}: wrote ${entries.length} files to ${normalizeToPosix(path.relative(ROOT_DIR, targetDir))}`
    );

    const entryLines = entries.map(
      ({ count, targetRelative }) =>
        `  "${count}": require("../../${targetRelative}"),`
    );

    exportBlocks.push(
      `export const ${exportName}: Partial<Record<string, number>> = {\n${entryLines.join("\n")}\n};`
    );
  }

  const output = `/* eslint-disable */\n// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by scripts/normalize-ios-cluster-markers.ts\n\n${exportBlocks.join("\n\n")}\n`;

  fs.writeFileSync(GENERATED_FILE, output, "utf8");
  console.log(
    `[normalize-ios-cluster-markers] done, canvas=${CANVAS_WIDTH}x${CANVAS_HEIGHT}, generated ${GENERATED_FILE}`
  );
};

void run();
