import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createCanvas, loadImage } from "canvas";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

// Locked uniform iOS full-sprite canvas – must match normalize-ios-full-markers.ts
const CANVAS_WIDTH = 322;
const CANVAS_HEIGHT = 138;
const PIN_ICON_WIDTH = 83;
const PIN_ICON_HEIGHT = 113;
const PIN_OFFSET_X = Math.round((CANVAS_WIDTH - PIN_ICON_WIDTH) / 2);
const PIN_OFFSET_Y = 0;

const STACKED_SOURCE_DIR = path.join(ROOT_DIR, "images/icons/stacked");
const TARGET_DIR = path.join(ROOT_DIR, "images/icons/ios-scaled/stacked-normalized");
const GENERATED_FILE = path.join(ROOT_DIR, "lib/maps/generatedIOSScaledStackedByCount.ts");

const STACKED_COUNTS = [2, 3, 4, 5, 6] as const;

const normalizeToPosix = (value: string) => value.replace(/\\/g, "/");

const run = async () => {
  fs.mkdirSync(TARGET_DIR, { recursive: true });

  const entries: Array<{ count: number; targetRelative: string }> = [];

  for (const count of STACKED_COUNTS) {
    const sourcePath = path.join(STACKED_SOURCE_DIR, `stacked_${count}.png`);
    if (!fs.existsSync(sourcePath)) {
      console.warn(`[normalize-ios-stacked-markers] missing source: ${sourcePath}`);
      continue;
    }

    const targetFileName = `stacked_${count}.png`;
    const targetPath = path.join(TARGET_DIR, targetFileName);

    const sourceImage = await loadImage(sourcePath);
    const canvas = createCanvas(CANVAS_WIDTH, CANVAS_HEIGHT);
    const ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);
    ctx.drawImage(sourceImage, PIN_OFFSET_X, PIN_OFFSET_Y, PIN_ICON_WIDTH, PIN_ICON_HEIGHT);

    fs.writeFileSync(targetPath, canvas.toBuffer("image/png"));

    const targetRelative = normalizeToPosix(
      path.relative(ROOT_DIR, targetPath)
    );
    entries.push({ count, targetRelative });
    console.log(
      `[normalize-ios-stacked-markers] wrote count=${count} -> ${targetRelative}`
    );
  }

  // Generate the TypeScript map file
  const entryLines = entries.map(
    ({ count, targetRelative }) =>
      `  ${count}: require("../../${targetRelative}"),`
  );

  const output = `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/normalize-ios-stacked-markers.ts

export const IOS_SCALED_STACKED_BY_COUNT: Partial<Record<number, number>> = {
${entryLines.join("\n")}
};
`;

  fs.writeFileSync(GENERATED_FILE, output, "utf8");
  console.log(
    `[normalize-ios-stacked-markers] done, entries=${entries.length}, canvas=${CANVAS_WIDTH}x${CANVAS_HEIGHT}`
  );
};

void run();
