import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },

  map: { flex: 1, width: "100%" },

  icon: { width: 64, height: 64 },

  dropdown_main: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    zIndex: 10,
  },
  branchOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 9,
  },
  branchOverlayHandle: {
    position: "relative",
    minHeight: 48,
    marginBottom: 8,
    paddingHorizontal: 16,
    zIndex: 2,
  },
  branchOverlayHandleToggle: {
    position: "absolute",
    right: 16,
    top: 0,
    zIndex: 3,
  },
  branchOverlayHandleToggleOpen: {
    top: -96,
  },
  branchOverlayHandleIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  branchOverlayHandleIconOpen: {
    transform: [{ rotate: "180deg" }],
  },
  categoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 0,
    paddingRight: 56,
  },
  categoryIconBtn: {
    height: 40,
    borderRadius: 20,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  categoryIcon: {
    width: 16,
    height: 16,
    resizeMode: "contain",
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111",
  },
  categoryLabelActive: {
    color: "white",
  },
  categoryIconBtnActive: {
    backgroundColor: "#EB8100",
  },

  backdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },

  searchField: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "white",
    borderRadius: 25,
    elevation: 1,
    borderWidth: 1,
    borderColor: "#eee",
    marginHorizontal: 16,
    marginTop: 12,
    gap: 5,
    marginBottom: 15,
  },
  searchIcon: { marginRight: 6 },
  searchInput: {
    flex: 1,
    paddingVertical: 0,
    color: "#111827",
    fontSize: 16,
  },
  card: {
    flex: 1,
    maxWidth: 200,
    marginRight: 24,
    backgroundColor: "white",
    borderRadius: 18,
    overflow: "hidden",
    zIndex: 2,

    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },

    elevation: 10,
  },

  row: {
    height: 44,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },

  menu: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E6E6E6",
  },

  menuRow: {
    height: 44,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E6E6E6",
    backgroundColor: "white",
  },

  rowIcon: { width: 18, height: 18 },

  rowTextBold: { flex: 1, fontWeight: "700" },
  rowText: { flex: 1, fontWeight: "500" },

  caret: { width: 16, height: 16, opacity: 0.7 },
  caretOpen: { transform: [{ rotate: "180deg" }] },

  plus: { width: 18, textAlign: "center", fontSize: 18, fontWeight: "600" },

  actionsRow: {
    flexDirection: "row",
    gap: 12,
    zIndex: 2,
  },
  roundBtn: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  locationSheetContainer: {
    zIndex: 20,
    elevation: 20,
  },
  locationSheetSearchBackground: {
    backgroundColor: "#B3B3B3",
  },
  locationSheetContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    justifyContent: "space-between",
  },
  locationSheetContentMap: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  locationSheetTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111",
    lineHeight: 24,
    includeFontPadding: false,
  },
  locationHeaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111",
    lineHeight: 24,
    includeFontPadding: false,
  },
  locationHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  locationHeaderRowSingle: {
    minHeight: 32,
    justifyContent: "center",
    marginBottom: 16,
  },
  locationBackButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  locationField: {
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  locationFieldLabel: {
    fontSize: 16,
    color: "#9CA3AF",
    marginBottom: 4,
    fontWeight: "500",
    lineHeight: 20,
  },
  locationFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  locationFieldValue: {
    fontSize: 16,
    color: "#111",
    fontWeight: "600",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationInput: {
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    fontWeight: "600",
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationInputPlaceholder: {
    color: "#9CA3AF",
    fontWeight: "500",
  },
  locationInputSecondary: {
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    marginTop: 0,
    fontWeight: "600",
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationInputSecondaryPlaceholder: {
    color: "#9CA3AF",
    fontWeight: "500",
  },
  locationPrimaryButton: {
    backgroundColor: "#111",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
  },
  locationPrimaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  locationOrRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 14,
  },
  locationOrLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  locationOrText: {
    marginHorizontal: 10,
    fontSize: 12,
    fontWeight: "600",
    color: "#9CA3AF",
  },
  locationSecondaryButton: {
    backgroundColor: "#EB8100",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
  },
  locationSecondaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  locationSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    fontWeight: "600",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationSearchList: {
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  locationSearchItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E6E6E6",
  },
  locationSearchItemLast: {
    borderBottomWidth: 0,
  },
  locationSearchText: {
    flex: 1,
  },
  locationSearchTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationSearchSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 2,
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationMapStep: {
    flex: 1,
  },
  locationMapWrapper: {
    position: "relative",
    flex: 1,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
    marginBottom: 16,
  },
  locationMapActions: {
    paddingBottom: 4,
  },
  locationMap: {
    flex: 1,
  },
  locationMapOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  locationMapLabel: {
    backgroundColor: "#111",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  locationMapLabelText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  locationMapPin: {
    width: 28,
    height: 28,
  },
  locationMapCenterButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 3,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.7)",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  locationMapHint: {
    backgroundColor: "#111",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    alignItems: "center",
  },
  locationMapHintText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  container_2: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 20,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 10,
    marginBottom: 20,
  },

  title: {
    fontSize: 18,
    fontWeight: "600",
  },

  filter_main: {
    flex: 1,
    flexDirection: "column",
  },
  filterScrollContent: {
    paddingBottom: 24,
  },
  filter_header: {
    flexDirection: "row",
    height: 50,
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 0.2,
    borderColor: "#E5E7EB",
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  filter_categories: {
    flexDirection: "column",
    width: "100%",
    paddingBottom: 10,
  },
  ratingSection: {
    marginBottom: 8,
  },
  ratingTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 10,
    marginTop: 22,
    marginBottom: 10,
  },
  ratingRow: {
    paddingRight: 10,
  },
  ratingChip: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 19,
    borderWidth: 1,
    borderColor: "#eee",
    backgroundColor: "#FFFFFF",
    marginRight: 10,
    marginTop: 10,
    marginLeft: 9,
  },
  ratingChipActive: {
    backgroundColor: "#EB8100",
    borderColor: "#EB8100",
  },
  ratingStar: {
    width: 16,
    height: 16,
  },
  ratingText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    marginLeft: 5,
  },
  ratingTextActive: {
    color: "#FFFFFF",
  },
});
