import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },

  map: { flex: 1, width: "100%" },

  icon: { width: 64, height: 64 },

  dropdown_main: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "flex-start",
    alignItems: "center",
    zIndex: 10,
  },
  branchOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 9,
  },
  branchOverlayHandle: {
    position: "relative",
    minHeight: 48,
    marginBottom: 8,
    paddingHorizontal: 16,
    zIndex: 2,
  },
  branchOverlayHandleToggle: {
    position: "absolute",
    right: 16,
    top: 0,
    zIndex: 3,
  },
  branchOverlayHandleToggleOpen: {
    top: -96,
  },
  branchOverlayHandleIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  branchOverlayHandleIconOpen: {
    transform: [{ rotate: "180deg" }],
  },
  categoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 0,
    paddingRight: 56,
  },
  categoryIconBtn: {
    height: 40,
    borderRadius: 20,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    ...(Platform.OS === "web"
      ? { boxShadow: "0 4px 8px rgba(0, 0, 0, 0.12)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.12,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 4 },
          elevation: 6,
        }),
  },
  categoryIcon: {
    width: 16,
    height: 16,
    resizeMode: "contain",
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111",
  },
  categoryLabelActive: {
    color: "white",
  },
  categoryIconBtnActive: {
    backgroundColor: "#EB8100",
  },

  backdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },

  searchTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginHorizontal: 17,
    marginTop: 12,
    marginBottom: 15,
    height: 42,
  },
  searchScreen: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FFFFFF",
    zIndex: 30,
  },
  searchBackButton: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    ...(Platform.OS === "web"
      ? { boxShadow: "0px 3px 10px rgba(0, 0, 0, 0.1)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.1,
          shadowRadius: 10,
          shadowOffset: { width: 0, height: 3 },
          elevation: 4,
        }),
    alignItems: "center",
    justifyContent: "center",
  },
  searchInputWrapper: {
    flex: 1,
    maxWidth: 458,
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    backgroundColor: "white",
    borderRadius: 20,
    gap: 8,
    ...(Platform.OS === "web"
      ? { boxShadow: "0px 3px 10px rgba(0, 0, 0, 0.1)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.1,
          shadowRadius: 10,
          shadowOffset: { width: 0, height: 3 },
          elevation: 4,
        }),
  },
  searchIcon: { marginRight: 0 },
  searchInput: {
    flex: 1,
    paddingVertical: 0,
    color: "#000000",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    includeFontPadding: false,
  },
  searchClearButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    flex: 1,
    maxWidth: 200,
    marginRight: 24,
    backgroundColor: "white",
    borderRadius: 18,
    overflow: "hidden",
    zIndex: 2,
    ...(Platform.OS === "web"
      ? { boxShadow: "0 6px 12px rgba(0, 0, 0, 0.14)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.14,
          shadowRadius: 12,
          shadowOffset: { width: 0, height: 6 },
          elevation: 10,
        }),
  },

  row: {
    height: 44,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },

  menu: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E6E6E6",
  },

  menuRow: {
    height: 44,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E6E6E6",
    backgroundColor: "white",
  },

  rowIcon: { width: 18, height: 18 },

  rowTextBold: { flex: 1, fontWeight: "700" },
  rowText: { flex: 1, fontWeight: "500" },

  caret: { width: 16, height: 16, opacity: 0.7 },
  caretOpen: { transform: [{ rotate: "180deg" }] },

  plus: { width: 18, textAlign: "center", fontSize: 18, fontWeight: "600" },

  actionsRow: {
    flexDirection: "row",
    gap: 12,
    zIndex: 2,
  },
  roundBtn: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 5px 10px rgba(0, 0, 0, 0.12)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.12,
          shadowRadius: 10,
          shadowOffset: { width: 0, height: 5 },
          elevation: 8,
        }),
  },
  actionBtnIcon: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  filterActiveIndicator: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 12,
    height: 12,
  },
  locationSheetContainer: {
    zIndex: 20,
    elevation: 20,
  },
  locationSheetSearchBackground: {
    backgroundColor: "#B3B3B3",
  },
  locationSheetContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    justifyContent: "space-between",
  },
  locationSheetContentMap: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  locationSheetTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111",
    lineHeight: 24,
    includeFontPadding: false,
  },
  locationHeaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111",
    lineHeight: 24,
    includeFontPadding: false,
  },
  locationHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  locationHeaderRowSingle: {
    minHeight: 32,
    justifyContent: "center",
    marginBottom: 16,
  },
  locationBackButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  locationField: {
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  locationFieldLabel: {
    fontSize: 16,
    color: "#9CA3AF",
    marginBottom: 4,
    fontWeight: "500",
    lineHeight: 20,
  },
  locationFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  locationFieldValue: {
    fontSize: 16,
    color: "#111",
    fontWeight: "600",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationInput: {
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    fontWeight: "600",
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationInputPlaceholder: {
    color: "#9CA3AF",
    fontWeight: "500",
  },
  locationInputSecondary: {
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    marginTop: 0,
    fontWeight: "600",
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationInputSecondaryPlaceholder: {
    color: "#9CA3AF",
    fontWeight: "500",
  },
  locationPrimaryButton: {
    backgroundColor: "#111",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
  },
  locationPrimaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  locationOrRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 14,
  },
  locationOrLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  locationOrText: {
    marginHorizontal: 10,
    fontSize: 12,
    fontWeight: "600",
    color: "#9CA3AF",
  },
  locationSecondaryButton: {
    backgroundColor: "#EB8100",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
  },
  locationSecondaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  locationSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: "#111",
    paddingVertical: 0,
    fontWeight: "600",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationSearchList: {
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  locationSearchItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E6E6E6",
  },
  locationSearchItemLast: {
    borderBottomWidth: 0,
  },
  locationSearchText: {
    flex: 1,
  },
  locationSearchTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    lineHeight: 20,
    includeFontPadding: false,
  },
  locationSearchSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 2,
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationMapStep: {
    flex: 1,
  },
  locationMapWrapper: {
    position: "relative",
    flex: 1,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
    marginBottom: 16,
  },
  locationMapActions: {
    paddingBottom: 4,
  },
  locationMap: {
    flex: 1,
  },
  locationMapOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  locationMapLabel: {
    backgroundColor: "#111",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  locationMapLabelText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  locationMapPin: {
    width: 28,
    height: 28,
  },
  locationMapCenterButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 3,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.7)",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.2,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 2 },
          elevation: 6,
        }),
  },
  locationMapSelectionCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(17, 17, 17, 0.92)",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 8px 24px rgba(0, 0, 0, 0.22)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.22,
          shadowRadius: 16,
          shadowOffset: { width: 0, height: 6 },
          elevation: 10,
        }),
  },
  locationMapSelectionTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 20,
    includeFontPadding: false,
    marginBottom: 2,
  },
  locationMapSelectionSubtitle: {
    color: "rgba(255, 255, 255, 0.82)",
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
    includeFontPadding: false,
  },
  locationMapHint: {
    backgroundColor: "#111",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    alignItems: "center",
  },
  locationMapHintText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  locationMapHeartButton: {
    alignSelf: "center",
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E11D48",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 10px 24px rgba(225, 29, 72, 0.28)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.22,
          shadowRadius: 14,
          shadowOffset: { width: 0, height: 6 },
          elevation: 10,
        }),
  },
  container_2: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 20,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 10,
    marginBottom: 20,
  },

  title: {
    fontSize: 18,
    fontWeight: "600",
  },

  filter_main: {
    flex: 1,
    flexDirection: "column",
  },
  filterScrollContent: {
    paddingBottom: 12,
  },
  filter_header: {
    flexDirection: "row",
    height: 50,
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 0.2,
    borderColor: "#E5E7EB",
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  filter_categories: {
    flexDirection: "column",
    width: "100%",
    paddingBottom: 10,
  },
  ratingSection: {
    marginBottom: 8,
  },
  ratingTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 10,
    marginTop: 22,
    marginBottom: 10,
  },
  ratingRow: {
    paddingRight: 10,
  },
  ratingChip: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 19,
    borderWidth: 1,
    borderColor: "#eee",
    backgroundColor: "#FFFFFF",
    marginRight: 10,
    marginTop: 10,
    marginLeft: 9,
  },
  ratingChipActive: {
    backgroundColor: "#EB8100",
    borderColor: "#EB8100",
  },
  ratingStar: {
    width: 16,
    height: 16,
  },
  ratingEmoji: {
    fontSize: 16,
    lineHeight: 16,
  },
  ratingEmojiActive: {
  },
  ratingText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    marginLeft: 5,
  },
  ratingTextActive: {
    color: "#FFFFFF",
  },
  filterSheetBackground: {
    backgroundColor: "transparent",
  },
  filterSheetHandle: {
    height: 0,
  },
  filterSheetHandleIndicator: {
    width: 0,
    height: 0,
  },
  filterDrawerWrapper: {
    flex: 1,
    alignItems: "flex-end",
  },
  filterDrawerPanel: {
    width: "85%",
    maxWidth: 326,
    minWidth: 280,
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    alignSelf: "flex-end",
    overflow: "visible",
  },
  filterDrawerHandle: {
    position: "absolute",
    left: -22,
    top: "45%",
    width: 22,
    height: 54,
    backgroundColor: "#EB8100",
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  filterDrawerHandleLine: {
    width: 16,
    height: 3,
    backgroundColor: "#FFFFFF",
    borderRadius: 2,
  },
  filterScroll: {
    flex: 1,
  },
  filterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  filterHeaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 24,
    color: "#000000",
  },
  filterHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filterHeaderReset: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
  },
  filterCloseButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#C7C7C7",
  },
  filterCloseText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#C7C7C7",
  },
  filterSection: {
    marginTop: 16,
  },
  filterSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 21,
    color: "#000000",
  },
  filterChips: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    columnGap: 12,
    rowGap: 12,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#E4E4E7",
    backgroundColor: "#FFFFFF",
  },
  filterChipActive: {
    backgroundColor: "#EB8100",
    borderColor: "#EB8100",
  },
  filterChipEmoji: {
    fontSize: 15,
    lineHeight: 18,
  },
  filterChipText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000000",
    includeFontPadding: false,
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  filterRatingChip: {
    minWidth: 70,
  },
  filterApplyRow: {
    paddingTop: 12,
  },
  filterApplyButton: {
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "#EB8100",
    alignItems: "center",
    justifyContent: "center",
  },
  filterApplyText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
});
